---
- name: New user is created
  hosts: 127.0.0.1
  become: true
  gather_facts: false
  connection: local
  vars:
    username:
      test:
        uname: test
        description: Test User Account

    myusers:
     - user1
     - user2
     - user3

  tasks:
    
    - name: Create multiple users
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ myusers }}"   

    - name: User gets created
      user: 
        name: "{{ username['test']['uname'] }}"
        comment: "{{ username['test']['description'] }}"
        state: present
 
