---
- name: New user is created
  hosts: 127.0.0.1
  become: true
  gather_facts: false
  vars:
    username:
      test:
        uname: test
        description: Test User Account

    myusers:
     - user1
     - user2
     - user3

  tasks:
    
    - name: run apt-get update and install python
      raw: "{{ item }}"
      loop:
        - sudo yum update -y
        - sudo yum install python -y
      become: true
      ignore_errors: true

    - name: Create multiple users
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ myusers }}"   

    - name: Load variable from encrypted file
      include_vars:
              file: secret

    - name: Display the encrypted variable
      debug:
        msg: "{{ secret }}"      
      no_log: true

    - name: User gets created
      user: 
        name: "{{ username['test']['uname'] }}"
        comment: "{{ username['test']['description'] }}"
        state: present
 
